# Generated by Django 4.2.13 on 2024-06-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_category_todoitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Study', 'Study'), ('Health', 'Health'), ('Home', 'Home'), ('Other', 'Other')], max_length=100),
        ),
    ]
